### ISSUE TITLE
FileReader.readAsText: Argument 1 is not an object error

### ISSUE THREAD

**Issue by hippo-m** [lgarron/clipboard-polyfill#164]
The for in loop structure in the #promiseRecordMap method returns another key called 'pushArray' in addition to the list of keys, which is why the problem occurs.

**Comment by hippo-m** [comment]
Fix PR: https://github.com/lgarron/clipboard-polyfill/pull/165

**Comment by lgarron** [comment]
Do you have a repro demonstrating this issue?

**Comment by mahmutisci** [comment]
Yes, I do have it, but since it's in a private repository, I can't share the repo. However, I typically use the polyfill in the following standard way:
`clipboard.write([
    new ClipboardItem({
        "text/plain": new Blob([plainText], {type: "text/plain"}),
        "text/html": new Blob([html], {type: "text/html"})
    })
]);
`
for some reason, using a 'for in' loop, as I mentioned above, causes the issue; it might be due to my webpack configurations, but it seemed more appropriate to use a legacy 'for' loop instead of 'for in' for an array. That's why I made the change and created a PR.

**Comment by lgarron** [comment]
The reason I'm asking is because this usually doesn't happen unless part of your code is tampering with global prototypes. This is very liable to cause trouble, and generally bad practice. I'm reluctant to add a workaround if I don't understand the full use case, because the fix might not be as simple as it seems.

**Comment by mahmutisci** [comment]
You might be right, but I don't believe it's due to global prototypes. I encountered a similar issue, and when debugging, I realized the source of the problem was here. While examining the code, I couldn't understand the use of 'for in'. I noticed that in the subsequent loop usage with the 'keys' variable, a 'for' loop was used. Thinking that was the correct approach, I implemented a fix.

**Comment by lgarron** [comment]
> You might be right, but I don't believe it's due to global prototypes.

Hmm, I remain skeptical of this, given that:

1) `pushArray` does not appear in this repo,
2) there seem to be quite a few pieces of code on GitHub demonstrating people [putting this on `Array.prototype`](https://github.com/search?q=Array.prototype+pushArray&type=code), and
3) this is by far the most plausible way to end up with that property in the iterator.

I still suggest looking more carefully at your code for lurking issues related to this.

That said, I'm alright with the PR given that it maintains the same intended functionality.

**Comment by lgarron** [comment]
Alright, see if `v4.0.2` works better for you.
