### ISSUE TITLE
Convenience method to intercept user copy.

### ISSUE THREAD

**Issue by lgarron** [lgarron/clipboard-polyfill#58]
Maybe something like:

  interceptCopy(callback: () => null|ClipboardPolyfill.DT)

The callback would specify whether the to overwrite the data on the clipboard event, and with what.
Ideally, we would pass a parameter to the callback to tell them if the event was user-initiated, but I don't think there's a nice way to do this without e.g. swizzling `document.execCommand` (Fields like `event.isTrusted` don't help.)

Should the callback be synchronous?

- A synchronous callback allows us to modify `event.clipboardData` in the event listener itself.
- A synchronous event listener does not allow the callback to make asynchronous calculations.
- In some browsers, synchronous modification of `event.clipboardData` may be buggy.
- In some browsers, we may be able to trigger `document.execCommand()` an additional time, either inside the initial handler, or using `setTimeout()`. This may be buggy in different situations.

Requested by @thomasjm

**Comment by lgarron** [comment]
(Maybe this should go into another package, though?)

**Comment by thomasjm** [comment]
Cool, thanks for opening this. A few thoughts:

* Can the callback receive information about what was actually copied, for it to inspect? I guess a `ClipboardPolyfill.DT`.
* If a copy was not user-initiated, I wouldn't want the callback to happen at all. The point of `interceptCopy` is to intercept user-initiated copies--why would I need to intercept a copy I initiated myself? Maybe it should even be called `interceptUserCopy`. (If a copy was not initiated by the user, then presumably it was initiated by `clipboard-polyfill`, right? It should be possible to know when an event is due to the library itself.)
* I don't quite understand what the semantics of an asynchronous callback would be. What if the user did a paste before the async action was completed? They would get the original, un-intercepted copy data, right? I think synchronous is fine--I wouldn't expect to be able to do time-consuming things in event handlers anway. (If you need to do an additional async call to `execCommand` under the hood because of browser bugginess that's fine, as long as there's a very short window in which the user could potentially sneak in a paste and get the wrong result.)

**Comment by thomasjm** [comment]
Actually, maybe there are some use-cases where you'd want to intercept copies you initiated yourself. And maybe copies can be initiated outside of this library. But in any case, I don't think the "user-initiated" flag is super necessary--if the client of this library is in the business of triggering their own copies, and they want to ignore them in the intercept function, it's not too unreasonable to make them handle that themselves.

**Comment by lgarron** [comment]
This project is now in maintenance mode purely as a polyfill for the async clipboard API, so this is out of scope now.
