### ISSUE TITLE
Replace DT.forEach with DataTransfer-compatible iteration.

### ISSUE THREAD

**Issue by lgarron** [lgarron/clipboard-polyfill#64]

**Comment by opusonline** [comment]
Hi,

as far as I know, you can only iterate over the `items` object within the `DataTransfer` instance. You already have the `m` object. Why not simply add the additional `items` object as an `Array` and in case of `setData`, after `this.m[type] = value;` simply call `this.items.push({type: type, value: value})`. Of course it's not that easy, because you should handle the case if an existing type gets overridden so the items entry must be removed accordingly.

Hope this helps.

**Comment by opusonline** [comment]
It would be nice to also have the `clearData` function on `clipboard.DT` instance.
`this.m = {}; this.items.length = 0;`

**Comment by lgarron** [comment]
We now use `ClipboardItem`.
