### ISSUE TITLE
WriteText does not work for Edge version 40. Works for version 41

### ISSUE THREAD

**Issue by sahilbahl** [lgarron/clipboard-polyfill#82]
I am currently using the below code. This seems to work for all browsers ( Chrome, Firefox, IE) but is broken for Edge. 
Version: 40.15063

`clipboard.writeText(copyStr).then(function success() {
			alert(copyStr + '\n\n' + 'Copied To clipboard'));
		}, function fail(error) {
			console.log('Copy failed');
		});`

**Comment by lgarron** [comment]
Could you log the error to see where it failed?

    clipboard.writeText(copyStr).then(function success() { alert(copyStr + '\n\n' + 'Copied To clipboard')); }, function fail(error) { console.log(error); });

**Comment by sahilbahl** [comment]
There is no error that occurred. It just does not copy the text.
I checked and this does not work even in Edge 38. Only working in latest Edge 41.

**Comment by lgarron** [comment]
I can't download a test VM for this right now, but I'll take a look when I can.

**Comment by sahilbahl** [comment]
Any update on this one ??

**Comment by lgarron** [comment]
I've tried to download Edge 40, and still I can't seem to find a way to do it on desktop. :-/
(And I don't have an XBox or Windows mobile phone.)

Do you know of a way to download older versions of Edge for testing?

**Comment by lgarron** [comment]
Could you help me pinpoint the version of EdgeHTML by reporting the user agent?
https://www.google.com/search?q=what%27s+my+user+agent&oq=what%27s+my+user+agent&aqs=chrome..69i57.2053j0j1&sourceid=chrome&ie=UTF-8

**Comment by lgarron** [comment]
Okay, I was able to reproduce as follows:

- Open EdgeHTML 16 or EdgeHTML 15 on BrowserStack.
- Try to copy *without opening F12 Developer Tools*.

It appears to trigger https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14495220/ due to

https://github.com/lgarron/clipboard-polyfill/blob/6fcad9b769adcf7f4ebca59520a3cb592c77df52/clipboard-polyfill.ts#L12-L15

The solution seems to be to avoid binding the console to `warnOrLog` during initial evaluation:

    var warnOrLog = function() {
        (console.warn || console.log).apply(console, arguments);
    }; // IE9 workaround (can't bind console functions).
    var warn = warnOrLog.bind(console, "[clipboard-polyfill]");

(And also to do something similar for the test page.)

**Comment by lgarron** [comment]
Okay, could you let me know if v2.4. fixes this for you?

**Comment by lgarron** [comment]
Reopening so I don't lose track until I have confirmation that the fix works.

**Comment by lgarron** [comment]
@sahilbahl, any chance you have some time to test this?
