### ISSUE TITLE
Sign release commits

### ISSUE THREAD

**Issue by lgarron** [lgarron/clipboard-polyfill#95]

**Comment by Favna** [comment]
Just in case you're not aware since it generally would require looking at the MAN doc, the easiest way for this is:

```sh
npm version <patch|minor|major> #depending on the version increase
git commit -s --amend --no-edit
``` 

Explanation:

`npm version <patch|minor|major>` bumps the package.json version by whatever you specify while adhering semantic versioning. For example `major` from `2.72.89` would go `3.0.0` or minor from same `2.73.0`. It then creates a git commit of `v<whatever_new_version>` and a matching tag (both that `v` and the tag creation can be configured) 

`git commit -s --amend --no-edit` amends the commit that was just created. `-s` specifies that you want to add a `Signed off by AUTHOR <EMAIL>` wherein AUTHOR and EMAIL are the ones you configured in `~/.gitconfig` (`%USERPROFILE%/.gitconfig` on windows) (or through `git config --global user.email` etc) and finally `--no-edit` specifies that it shouldn't open the as-configured default git text editor to edit the commit message.

Naturally you can also automate all of this with a bash Function:

```sh
#!/bin/bash

function librelease() {
  if [[ $1 == major ]] || [[ $1 == minor ]] || [[ $1 == patch ]]
    then
      npm version "$1"
      git commit -s --amend --no-edit
    else
      echo "Please provide either major, minor or patch as first argument to this function"
  fi
}
```

**Comment by lgarron** [comment]
I was referring specifically to signing commits using something like GPG (or S/MIME). The ecosystem doesn't really use this for verification, and I would prefer not to complicate building/publishing any more than needed, so I'm not going to do this any time soon.
