### ISSUE TITLE
TypeError: this.write is not a function

### ISSUE THREAD

**Issue by jarmo** [lgarron/clipboard-polyfill#99]
I'm receiving an error message `TypeError: this.write is not a function` when using `clipboard.writeText("foo")` on Firefox 62.0. Am I doing something wrong?

**Comment by lgarron** [comment]
Hmm, https://garron.net/code/clipboard-polyfill/ works for me.
Could you let me know more about the environment where this fails?

**Comment by jarmo** [comment]
I'm calling it inside of a click handler this this:

```js
document.getElementById("btn")
  .addEventListener("click", function(event) {
    clipboard.writeText("foo")
  })
```

Should work even after reading #77. Or?

I'm using brunch.io and importing polyfill like this:
```js
import clipboard from "clipboard-polyfill"
```

**Comment by lgarron** [comment]
> I'm calling it inside of a click handler this this:
> 
> ```js
> document.getElementById("btn")
>   .addEventListener("click", function(event) {
>     clipboard.writeText("foo")
>   })
> ```

This should definitely work, and when I try it in Firefox it does.

Is there any chance that `clipboard.writeText` is shaken out of the tree, e.g. because static analysis assumes that `navigator.clipboard` is present?

https://github.com/lgarron/clipboard-polyfill/blob/1b16a2dbe2046688dcf191ae99ba50d9d3b08397/clipboard-polyfill.ts#L89-L95

If not, would you mind putting up a minimal repro case somewhere?

**Comment by lgarron** [comment]
See https://github.com/lgarron/clipboard-polyfill/issues/77#issuecomment-432518818
